### ISSUE TITLE
Webtoon mode

### ISSUE THREAD

**Issue by kidburglar** [jonathanpoelen/manga-viewer#1]
Hello,

I give a try at your project, and it's pretty nice and easy to use for any manga/comics.

Do you have plan to maybe have a "webtoon mode"? I'm not sure if it's really easy to do something others than displaying all the pictures vertically, but maybe it will be heavy if the folders are very big?

**Comment by jonathanpoelen** [comment]
This mode already exists by pressing `l` (lowercase L) :)

I updated the script to be more user-friendly to configure and an option to display the default shortcuts (`htmlviewer -p`).

**Comment by kidburglar** [comment]
Thanks that was fast ^^

I see there are nice new options.
I really like that it's only html and js before I used other comics reader ^^

I still think that maybe for webtoon having all the pages following could be better. I think it's what do webtoon on their website.
Maybe for avoiding to load too much pages in the "webtoon mode" it could be some kind of page limite that could be changed.
What do you think?

**Comment by jonathanpoelen** [comment]
> Thanks that was fast ^^

In fact I started wednesday ^^. This script is over 7 years old, I took advantage of creating a separate repository to make it evolve.

Something like `mode webtoon [page_limit=0]` which shows all images in a chapter. Basically, a `mode single` by chapter ? And I also add `page_limit` to `mode single` because it's good.

**Comment by kidburglar** [comment]
Hello, sorry for y late response

Yes I think something like image_limit=0 would be great.
I not really see what you mean by "mode single by chapter" but you can do a first time how you think it would be good and I will see ^^

In html/js the possibilities are kinda unlimited I will need to give it a real try reading something to see how it feel

**Comment by jonathanpoelen** [comment]
Hello, I implemented the webtoon mode, what do you think ?

**Comment by kidburglar** [comment]
Hello

I just tested the -m webtoon and it looks perfect for me ^^. Thanks.

I'm sure I will have few more ideas but I want first look add the commands but I will surely do another issue. I think it would be easier too ^^

**Comment by jonathanpoelen** [comment]
Super, I close this issue.
